### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by mosabua** [joakime/android-sdkfido#4]
here is how.. 

[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sdkfido ---
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/target/sdkfido-1.0-SNAPSHOT.jar to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT.jar
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/pom.xml to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT.pom
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/target/sdkfido-1.0-SNAPSHOT-sources.jar to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT-sources.jar
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/target/sdkfido-1.0-SNAPSHOT-javadoc.jar to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT-javadoc.jar
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/target/sdkfido-1.0-SNAPSHOT-bin.tar.gz to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT-bin.tar.gz
[INFO] Installing /opt/java/dev/github/android-sdkfido/sdkfido/target/sdkfido-1.0-SNAPSHOT-bin.zip to /Users/manfred/.m2/repository/net/erdfelt/android/sdkfido/sdkfido/1.0-SNAPSHOT/sdkfido-1.0-SNAPSHOT-bin.zip
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building SDKFido :: GUI Client 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/erdfelt/android/sdkfido/sdkfido-lib/1.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/erdfelt/android/sdkfido/sdkfido-lib/1.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/erdfelt/android/sdkfido/sdkfido-lib/1.0-SNAPSHOT/sdkfido-lib-1.0-SNAPSHOT.pom
[WARNING] The POM for net.erdfelt.android.sdkfido:sdkfido-lib:jar:1.0-SNAPSHOT is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/erdfelt/android/sdkfido/sdkfido-lib/1.0-SNAPSHOT/sdkfido-lib-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SDKFido :: Parent ................................. SUCCESS [1.806s]
[INFO] SDKFido (Fetch!) .................................. SUCCESS [43.105s]
[INFO] SDKFido :: GUI Client ............................. FAILURE [2.281s]
[INFO] SDKFido Maven Plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.336s
[INFO] Finished at: Fri May 27 12:09:33 PDT 2011
[INFO] Final Memory: 18M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sdkfido-ui: Could not resolve dependencies for project net.erdfelt.android.sdkfido:sdkfido-ui:jar:1.0-SNAPSHOT: Could not find artifact net.erdfelt.android.sdkfido:sdkfido-lib:jar:1.0-SNAPSHOT in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sdkfido-ui

**Comment by joakime** [comment]
Fixed.  It was an ancient dependency leftover.
I had it in my local repo, so it never complained, stupid me. :-(
