### ISSUE TITLE
wrong command line on readme

### ISSUE THREAD

**Issue by mosabua** [joakime/android-sdkfido#5]
java -Xmx512m -jar target/sdkfido-1.0-SNAPSHOT.jar --outputType MAVEN_MULTI --outputDirectory $HOME/maven-android froyo

should be

java -Xmx512m -jar target/sdkfido-1.0-SNAPSHOT.jar --outputType MAVEN_MULTI --outputDir $HOME/maven-android froyo

see the --outputDir parameter

**Comment by joakime** [comment]
Fixed (along with another)
